# Do not edit. Generated by the configure script.
export PATH:=/home/ubuntu/MentoriaMuriloSerafim/backend/node-v14.13.1/out/tools/bin:$(PATH)
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.5
PREFIX=/usr
BUILDTYPE=Release
